import Header from './_components/header'

import type { Metadata } from 'next'

import '@/styles/globals.scss'
import { Montserrat } from 'next/font/google'
import Footer from './_components/footer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sciflutter',
  description: 'Generated by create next app',
}

interface Props {
  children: React.ReactNode
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang='en'>
      <body className={montserrat.className}>
        <Header />

        <main className='container container--main'>
          {children}
        </main>

        <Footer />
      </body>
    </html>
  )
}

export default RootLayout