import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'

import '@/styles/globals.scss'
import LayoutApp from './_components/layoutApp'
import Header from './_components/header'
import Footer from './_components/footer'
import PageSkeleton from './_skeletons/pageSkeleton'
import dynamic from 'next/dynamic'
import NavBarSkeleton from './_skeletons/navBarSkeleton'
import NavBar from './_components/navBar'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sciflutter',
  description: 'Generated by create next app',
}

const DynamicApp = dynamic(() => import('./_components/layoutApp'), { loading: () => <PageSkeleton /> })

interface Props {
  children: React.ReactNode
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <DynamicApp>{children}</DynamicApp>
      </body>
    </html>
  );
}

export default RootLayout